[colors.bright]
black = "0x41505e"
blue = "0x5ec4ff"
cyan = "0x70e1e8"
green = "0x8bd49c"
magenta = "0xe27e8d"
red = "0xd95468"
white = "0xffffff"
yellow = "0xebbf83"

[colors.cursor]
cursor = "0x008b94"
text = "0xfafafa"

[colors.normal]
black = "0x333f4a"
blue = "0x539afc"
cyan = "0x70e1e8"
green = "0x8bd49c"
magenta = "0xb62d65"
red = "0xd95468"
white = "0xb7c5d3"

[colors.primary]
background = "0x171d23"
foreground = "0xffffff"

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u0006v"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006s"
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0006x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006h"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006j"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006k"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006l"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00061"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00062"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00063"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00064"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00065"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00066"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00067"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00068"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00069"
key = "Key9"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006H"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006J"
key = "Down"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006K"
key = "Up"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0006L"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Alt"

[scrolling]
history = 10000
multiplier = 3

[shell]
program = "/usr/local/bin/tmux"

[window]
decorations = "none"
dynamic_padding = false
dynamic_title = true
opacity = 0.8

[window.dimensions]
columns = 160
lines = 48

[window.padding]
x = 5
y = 0
